name: CI

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Setup Dependencies
      run: |
        python${{ matrix.python-version }} -m venv .venv
        source .venv/bin/activate
        pip install -r requirements-dev.txt

    - name: Setup Package
      run: |
        source .venv/bin/activate
        pip install .

    - name: Test
      run: |
        source .venv/bin/activate
        python -m pytest

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
    - name: set PY
      run: echo "::set-env name=PY::$(python --version --version | sha256sum | cut -d' ' -f1)"
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.0.0
