name: Test

on: [push]


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "pypy3"]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}

    - name: Install
      run: |
        pip install -e .
        pip install -r requirements-dev.txt

    - name: Test
      run: |
        pytest

